import Image from "next/image";
import { ArrowDownRight, ArrowRight, ArrowUpRight, Award, Building2, Check, ChevronRight, Download, Factory, Globe2, Mail, MapPin, Phone, Ruler, ShieldCheck, Sparkles, ThermometerSun, Wrench } from "lucide-react";
import ContactForm from "./contact-form";
import MobileMenu from "./mobile-menu";

const productSystems = [
  { name: "IDEAL 4000", group: "PVC prozori", image: "/images/stolarija_ideal_4000.jpg", value: "Uw 1,3", specs: ["5 komora", "70 mm dubine ugradnje", "2 zone dihtovanja", "Dvoslojno termo staklo"] },
  { name: "IDEAL NEO AD", group: "PVC prozori", image: "/images/stolarija_ideal_neo_ad.png", value: "Uw 1,0", specs: ["6 komora", "76 mm dubine ugradnje", "2 zone dihtovanja", "Troslojno termo staklo"] },
  { name: "IDEAL NEO MD", group: "PVC prozori", image: "/images/stolarija_ideal_neo_md.png", value: "Uw 0,86", specs: ["6 komora", "76 mm dubine ugradnje", "3 zone dihtovanja", "Troslojno termo staklo do 54 mm"] },
  { name: "IDEAL 8000", group: "PVC prozori", image: "/images/stolarija_ideal_8000.jpg", value: "Uw 0,76", specs: ["6 komora", "85 mm dubine ugradnje", "3 zone dihtovanja", "Troslojno termo staklo do 54 mm"] },
  { name: "EMERUS E50", group: "AL bravarija", image: "/images/PS50.png", value: "Uw 4,4", specs: ["Bez termičkog mosta", "50 mm dubine ugradnje", "Prozori i vrata", "RAL paleta · eloksirani EV1 profil"] },
  { name: "EMERUS PR65tt", group: "AL bravarija", image: "/images/PR65tt.png", value: "Uw 1,6", specs: ["Sa termičkim mostom", "65 mm dubine ugradnje", "2 zone dihtovanja", "Dvoslojno termo staklo"] },
  { name: "EMERUS PE85tt", group: "AL bravarija", image: "/images/PE85tt.png", value: "Uw 1,1", specs: ["Sa termičkim mostom", "77 mm dubine ugradnje", "2 zone dihtovanja", "Troslojno termo staklo"] },
];

const offer = [
  { number: "01", title: "PVC stolarija", text: "Petokomorni i šestokomorni aluplast profili, dvoslojno ili troslojno termoizolaciono staklo, argon i LOW-e premaz za visoku energetsku efikasnost.", image: "/images/stolarija_ideal_8000.jpg" },
  { number: "02", title: "AL bravarija", text: "Elegantni i dugotrajni EMERUS sistemi sa ili bez prekinutog termičkog mosta, u širokoj RAL paleti ili eloksiranoj EV1 izvedbi.", image: "/images/PE85tt.png" },
  { number: "03", title: "Ulazna vrata", text: "PVC i AL ulazna vrata po želji kupca, sa standardnim ili skrivenim krilom i prvoklasnim G-U sigurnosnim okovima.", image: "/images/vrata_emerus_pe85n.png" },
  { number: "04", title: "Klizni sistemi", text: "PVC smart-slide, AL podizno-klizni i višekrilni sistemi za maksimalno otvaranje prostora, terase i balkone.", image: "/images/pvc_smart-slide.jpg" },
  { number: "05", title: "Staklene fasade", text: "Kontinuirane EMERUS E50K fasade za velike staklene površine, snažnu statiku, vizuelnu lakoću i dobru termoizolaciju.", image: "/images/Staklene_fasade.png" },
  { number: "06", title: "Zimski vrtovi", text: "FEAL namjenski profili, mnogo prirodnog svjetla i rješenja prilagođena tipu ostakljenja i načinu pristupa vrtu.", image: "/images/zimski-vrt-profil.jpeg", presentation: true },
  { number: "07", title: "AL roletne i komarnici", text: "ALUPROF i EXTE–ELITE roletne u vanjskoj, podfasadnoj ili nadgradnoj izvedbi, uz plisse, rolo i fiksne komarnike.", image: "/images/roletne.jpg" },
  { number: "08", title: "Garažna vrata", text: "Sekciona garažna vrata u različitim bojama, formama i dezenima, sa prvoklasnim SOMFY elektromotornim pogonom.", image: "/images/garazna-vrata-somfy.jpeg", presentation: true },
  { number: "09", title: "AL ograde i kapije", text: "Dugotrajno rješenje za vaš balkon ili dvorište sa mnogo varijanti estetskog izgleda.", image: "/images/al-ograde-kapije.jpeg", presentation: true },
];

const doors = [["IDEAL 4000", "PVC · 5 komora · 70 mm dubine · standardno vidno krilo"], ["IDEAL 7000", "PVC · 6 komora · 85 mm dubine · standardno ili skriveno krilo"], ["EMERUS PE85tt", "AL · dvije zone dihtovanja · 77 mm dubine · standardno vidno krilo"], ["EMERUS E90tt", "AL · tri zone dihtovanja · 90 mm dubine · skriveno krilo · ekskluzivna vrata"]];
const sliders = [["PVC smart-slide", "140 mm dubine · dvoslojno/troslojno staklo · Uw do 1,0 W/m²K"], ["PVC HST 85", "200 mm dubine · dvoslojno/troslojno staklo · Uw 0,95 W/m²K"], ["AL PK150tt", "Podizno-klizni sistem sa PTM · 150 mm dubine"], ["AL E560S", "Bez PTM · 2–4 staze · 2–8 krila"], ["AL E65Stt", "Sa PTM · 2–3 staze · 2–6 krila"]];
const partners = [["aluplast", "/images/aluplast.png", "https://www.aluplast.net/eng-int/"], ["G-U", "/images/GU.png", "https://www.g-u.com/en/HR.html"], ["FEAL", "/images/feal.png", "https://feal.ba/en/"], ["EMINAL", "/images/eminal.png", "https://www.eminal.ba/"], ["EXTE", "/images/exte-logo.jpeg", "https://www.exte.de/en/"], ["Somfy", "/images/somfy-logo.svg", "https://www.somfy.com/"], ["Termoglas", "/images/termoglas.png", "https://www.termoglas.ba/"], ["Pavković paneli", "/images/pavkov.png", "https://www.pavkovic-paneli.com/"]];
const markets = ["Bosna i Hercegovina", "Hrvatska", "Austrija", "Njemačka", "Luksemburg", "Holandija"];

function BrandMark({ light = false }: { light?: boolean }) { return <a href="#top" className={`brand ${light ? "brand-light" : ""}`} aria-label="JAS PlastikAL — početna"><Image src="/images/logojas.png" alt="JAS PlastikAL" width={160} height={92} preload={!light} /></a>; }
function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="section-label"><span />{children}</p>; }

export default function Home() {
  const siteUrl = process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : "https://jasplastikal-website.vercel.app";
  const localBusinessSchema = { "@context": "https://schema.org", "@type": "HomeAndConstructionBusiness", name: "JAS PlastikAL", foundingDate: "2017", url: siteUrl, sameAs: ["https://www.jasplastikal.com/"], email: "info@jasplastikal.com", telephone: "+38761478480", address: { "@type": "PostalAddress", streetAddress: "Bosanska bb", postalCode: "74250", addressLocality: "Maglaj", addressCountry: "BA" }, areaServed: markets };
  return <main id="top">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }} />
    <a className="skip-link" href="#hero-title">Preskoči na sadržaj</a>
    <header className="site-header"><BrandMark /><nav className="desktop-nav" aria-label="Glavna navigacija"><a href="#o-nama">O nama</a><a href="#ponuda">Ponuda</a><a href="#sistemi">Sistemi</a><a href="#partneri">Partneri</a></nav><a className="header-cta" href="#kontakt">Zatraži ponudu <ArrowDownRight size={18} /></a><MobileMenu /></header>

    <section className="hero" aria-labelledby="hero-title"><div className="hero-grid" aria-hidden="true" /><div className="hero-copy"><p className="eyebrow"><Sparkles size={15} /> Proizvodnja i ugradnja od 2017.</p><h1 id="hero-title">Prostor počinje<br />dobrim <em>okvirom.</em></h1><p className="hero-lead">PVC i aluminijski sistemi projektovani da traju — od precizne proizvodnje u Maglaju do čiste, pouzdane montaže širom Evrope.</p><div className="hero-actions"><a className="button button-primary" href="#ponuda">Istraži ponudu <ArrowRight size={19} /></a><a className="button button-ghost" href="/JASPlastikAL-katalog-2024.pdf" download>Preuzmi katalog <Download size={18} /></a></div><div className="hero-proof" aria-label="Ključne prednosti"><div><strong>9+</strong><span>grupa proizvoda</span></div><div><strong>6</strong><span>evropskih tržišta</span></div><div><strong>CE</strong><span>certificirana proizvodnja</span></div></div></div><div className="hero-visual"><Image src="/images/Zimski_vrt.jpg" alt="JAS PlastikAL AL zimski vrt sa kliznim vratima" fill sizes="(max-width: 900px) 100vw, 50vw" loading="eager" fetchPriority="high" /><div className="hero-image-shade" /><div className="hero-grain" aria-hidden="true" /><div className="hero-scanline" aria-hidden="true" /><div className="hero-focus" aria-hidden="true"><span><i />Fokus / klizna vrata</span></div><div className="hero-rail" aria-hidden="true"><span>01</span><i /><span>03</span></div><div className="material-card"><span>Proizvod / 06</span><strong>ZIMSKI VRT</strong><small>FEAL aluminijski sistem · klizna vrata · mnogo prirodnog svjetla</small></div><div className="hero-badge"><ThermometerSun size={20} /><span>Sistem u<br /><strong>fokusu</strong></span></div></div><a className="scroll-cue" href="#o-nama"><span>Skrolaj za više</span><ArrowDownRight size={18} /></a></section>

    <section className="statement" id="o-nama"><SectionLabel>Ko smo mi</SectionLabel><div className="statement-grid"><h2>Kvalitet ne poznaje granice.</h2><div><p>JAS PlastikAL je specijalizirano društvo za proizvodnju i ugradnju PVC stolarije, AL bravarije, garažnih vrata, roletni, ograda, kapija, zimskih vrtova i aluminijskih konstrukcija.</p><p>Predan i temeljit rad pretvaramo u proizvode koji kupcima donose sigurnost, energetsku efikasnost i čist vizuelni identitet prostora.</p><a className="text-link" href="#kontakt">Razgovarajmo o projektu <ArrowRight size={17} /></a></div></div><div className="process-strip" aria-label="Proces rada"><div><span>01</span><Ruler size={26} /><strong>Mjerenje i savjetovanje</strong><p>Razumijemo prostor, potrebe i tehničke zahtjeve prije prve odluke.</p></div><div><span>02</span><Factory size={26} /><strong>Precizna proizvodnja</strong><p>Provjereni profili, vrhunski okovi i kontrola svakog detalja u Maglaju.</p></div><div><span>03</span><Wrench size={26} /><strong>Čista montaža</strong><p>Pouzdana ugradnja i završna provjera funkcije na vašem objektu.</p></div></div><div className="trust-strip"><div className="trust-intro"><Globe2 size={24} /><span>Povjerenje kupaca<br />širom Evrope</span></div><div className="markets">{markets.map((market) => <span key={market}>{market}</span>)}</div></div></section>

    <section className="offer-section" id="ponuda"><div className="section-heading inverse"><div><SectionLabel>Kompletna ponuda</SectionLabel><h2>Jedan partner.<br /><em>Cijeli objekat.</em></h2></div><p>Od prvog mjerenja do finalne montaže, biramo provjerene sisteme i prilagođavamo svaki detalj vašem projektu.</p></div><div className="offer-grid">{offer.map((item) => <a className={`offer-card${item.presentation ? " offer-card-product" : ""}`} href="#kontakt" aria-label={`Zatraži ponudu za: ${item.title}`} key={item.title}><div className="offer-image"><Image src={item.image} alt="" fill sizes="(max-width: 700px) 100vw, (max-width: 1100px) 50vw, 33vw" /></div><div className="offer-card-top"><span>{item.number}</span><ArrowDownRight size={22} /></div><div className="offer-card-copy"><h3>{item.title}</h3><p>{item.text}</p><span className="offer-cta">Zatraži ponudu <ArrowRight size={15} /></span></div></a>)}</div><div className="extra-offer"><span>+ Dodatno izrađujemo</span><p>AL konstrukcije i zavarivanje · zavjese · alu bond · nadstrešnice · konstrukcije predulaza · prozorske klupice · AL grilje · motori za kapije</p></div></section>

    <section className="systems-section" id="sistemi"><div className="section-heading"><div><SectionLabel>Provjereni sistemi</SectionLabel><h2>Brojevi koji<br /><em>čuvaju komfor.</em></h2></div><p>Uporedite reprezentativne PVC i AL sisteme. Sve izvedbe dostupne su u pripadajućim dekorima, RAL bojama ili sa ALU oblogama, zavisno od sistema.</p></div><div className="system-grid">{productSystems.map((system, index) => <article className={`system-card ${index === 3 ? "featured" : ""}`} key={system.name}>{index === 3 ? <span className="featured-badge">Najbolji Uw</span> : null}<div className="system-meta"><span>{system.group}</span><strong>{system.value}<small>{system.value.includes("Uw") ? " W/m²K" : ""}</small></strong></div><div className="system-image"><Image src={system.image} alt={`${system.name} profil`} fill sizes="(max-width: 700px) 100vw, 33vw" /></div><h3>{system.name}</h3><ul>{system.specs.map((spec) => <li key={spec}><Check size={14} />{spec}</li>)}</ul></article>)}</div><div className="detail-lists"><div><p className="detail-kicker">Ulazna vrata</p><h3>Sigurnost u prvom planu.</h3>{doors.map(([name, detail]) => <a className="detail-row" href="#kontakt" aria-label={`Upit za ${name}`} key={name}><strong>{name}</strong><span>{detail}</span><ChevronRight size={18} /></a>)}</div><div><p className="detail-kicker">Klizni sistemi</p><h3>Više svjetla. Više prostora.</h3>{sliders.map(([name, detail]) => <a className="detail-row" href="#kontakt" aria-label={`Upit za ${name}`} key={name}><strong>{name}</strong><span>{detail}</span><ChevronRight size={18} /></a>)}</div></div></section>

    <section className="cert-section"><div className="cert-image"><Image src="/images/certifikat.jpg" alt="CE certifikat JAS PlastikAL" fill sizes="(max-width: 800px) 100vw, 38vw" /></div><div className="cert-copy"><SectionLabel>Dokaz kvaliteta</SectionLabel><Award size={42} strokeWidth={1.4} /><h2>Certificirana<br />proizvodnja.</h2><p>CE certifikat potvrđuje da se proizvodnja PVC stolarije izvodi prema strogim kriterijima koje je propisao proizvođač.</p><div className="cert-points"><span><ShieldCheck size={19} /> Kontrolisan proces</span><span><Building2 size={19} /> Evropski sistemi</span></div></div></section>

    <section className="partners-section" id="partneri"><div className="section-heading compact"><div><SectionLabel>Naši partneri</SectionLabel><h2>Kvalitet počinje<br />pravim izborom.</h2></div><p>U proizvodnji koristimo sisteme i komponente etabliranih evropskih i svjetskih proizvođača.</p></div><div className="partner-grid">{partners.map(([name, logo, href]) => <a key={name} href={href} target="_blank" rel="noopener noreferrer" aria-label={`${name} — otvara partnersku stranicu u novom prozoru`}><Image src={logo} alt={name} width={180} height={80} /><ArrowUpRight size={16} /></a>)}</div></section>

    <section className="contact-section" id="kontakt"><div className="contact-main"><SectionLabel>Pokrenimo projekat</SectionLabel><h2>Imate otvor?<br /><em>Mi imamo rješenje.</em></h2><p>Pošaljite dimenzije, skicu ili samo ideju. Naš tim će vam pomoći da odaberete odgovarajući sistem za vaš objekat.</p><div className="contact-actions"><a className="button button-light" href="mailto:jasplastikal@gmail.com?subject=Upit%20za%20ponudu%20-%20JAS%20PlastikAL">Pošalji upit <Mail size={18} /></a><a className="button button-outline-light" href="tel:+38761478480">Pozovi nas <Phone size={18} /></a></div></div><div className="contact-side"><ContactForm /><div className="contact-info"><div><MapPin size={20} /><span><small>Adresa</small><a href="https://maps.google.com/?q=JAS+PlastikAL+Maglaj" target="_blank" rel="noopener noreferrer">Ul. Bosanska bb<br />74250 Maglaj, BiH</a></span></div><div><Phone size={20} /><span><small>Prodaja i informacije</small><a href="tel:+38761478480">Hodžić Asim · +387 61 478 480</a><a href="tel:+38762683524">Cvrčak Ajdin · +387 62 683 524</a><a href="tel:+38762235112">Cvrčak Saud · +387 62 235 112</a><a href="tel:+4915228531422">Zlatan Kepić · +49 1522 8531422</a></span></div><div><Mail size={20} /><span><small>Email</small><a href="mailto:info@jasplastikal.com">info@jasplastikal.com</a><a href="mailto:jasplastikal@gmail.com">jasplastikal@gmail.com</a></span></div></div></div><div className="map-wrap"><iframe title="JAS PlastikAL lokacija u Maglaju" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1120.140899342273!2d18.09715350001663!3d44.55545778645103!3m2!1i1024!1i768!4f13.1!3m3!1m2!1s0x475e8faf56522835%3A0xe250e17e29840165!2sJAS%20plastikAL%20doo!5e0!3m2!1sen!2sba!4v1694257369250!5m2!1sen!2sba" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></section>

    <a className="mobile-call" href="tel:+38761478480"><Phone size={17} /> Pozovi nas</a>

    <footer className="site-footer"><BrandMark light /><p>Proizvodnja i ugradnja PVC i AL sistema iz Maglaja za objekte širom Evrope.</p><div><a href="#ponuda">Ponuda</a><a href="#sistemi">Sistemi</a><a href="/JASPlastikAL-katalog-2024.pdf" download>Katalog</a><a href="#kontakt">Kontakt</a></div><div className="footer-bottom"><small>© {new Date().getFullYear()} JAS PlastikAL d.o.o. Sva prava zadržana.</small><small className="footer-credit">Dizajn i izrada web stranice <a href="https://www.h-cyber.de" target="_blank" rel="noopener noreferrer">H-Cyber</a></small></div></footer>
  </main>;
}
